// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ccgdrpphyhykstutsvga.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNjZ2RycHBoeWh5a3N0dXRzdmdhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU0Mjk5MjMsImV4cCI6MjA3MTAwNTkyM30.pudEr0IMHJvE9Sir44HiPjD_YDz4OiOXmNwS3F3aq7g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});